dist: trusty
sudo: false
language: node_js
node_js:
  - 6
  - 8
services:
  - mysql
  - postgresql
install: npm install -D
addons:
  postgresql: "9.4"
script: npm run ci
after_success: npm run codecov
